### PR TITLE
Fixed &nbsp; issue when previous line occupies entire width of line (available space)

### PR DESCRIPTION
**Pull request by Jagan-P**
- [x] built and tested the changes locally.
 - [] added/updated any applicable tests.
 - [] added/updated any applicable API documentation.
 - [] added/updated any applicable demos.

image

### CODE REVIEW

**Comment by trickeyone** [comment]
Thanks for the PR @Jagan-P ! Looks like there is a CI failure. Can you fix and re-push?

**Comment by Jagan-P** [comment]
Done @trickeyone.

**Comment by Jagan-P** [comment]
@trickeyone could you please merge this? We might need this as npm package. Thanks in advance.

**Comment by trickeyone** [comment]
@Jagan-P I'll try to get a release out today

**Comment by Jagan-P** [comment]
Thanks again!

**Comment by Jagan-P** [comment]
@trickeyone could you please release this update in npm when you are find some time? Thanks in advance!

**Comment by trickeyone** [comment]
@Jagan-P My apologies. Work got in the way. Version 7.0.3 with this fix has been published to npm and is now available. Thank you again for your contribution!

**Pull request merged**
